# Generated by Django 6.1.1 on 2026-10-02 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용 중인 닉네임입니다.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nickname', message='닉네임은 한글, 영문, 숫자, 밑줄만 쓸 수 있고 2자 이상 20자 이하여야 합니다.', regex='\\A[가-힣a-zA-Z0-9_]{2,20}\\Z')], verbose_name='닉네임'),
        ),
    ]
