# Generated by Django 6.1.1 on 2026-10-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=0, verbose_name='세션 버전'),
        ),
    ]
