# Generated by Django 6.1.1 on 2026-10-02 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_token_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('signup', '가입 인증'), ('login', '로그인 인증'), ('password_reset', '비밀번호 재설정')], max_length=20, verbose_name='용도')),
                ('code_hash', models.CharField(blank=True, max_length=64, verbose_name='코드 해시')),
                ('expires_at', models.DateTimeField(verbose_name='만료 시각')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='틀린 횟수')),
                ('last_issued_at', models.DateTimeField(verbose_name='마지막 발급 시각')),
                ('window_started_at', models.DateTimeField(verbose_name='발급 횟수를 세기 시작한 시각')),
                ('issued_in_window', models.PositiveSmallIntegerField(default=0, verbose_name='구간 안의 발급 횟수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '인증 코드',
                'verbose_name_plural': '인증 코드',
                'constraints': [models.UniqueConstraint(fields=('user', 'purpose'), name='accounts_emailcode_user_purpose_unique')],
            },
        ),
    ]
