# Generated by Django 6.1.1 on 2026-10-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mark_existing_users_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='받는 사람')),
                ('subject', models.CharField(max_length=200, verbose_name='제목')),
                ('body', models.TextField(blank=True, verbose_name='본문')),
                ('status', models.CharField(choices=[('pending', '발송 대기'), ('discarded', '버림')], default='pending', max_length=20, verbose_name='상태')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='시도 횟수')),
                ('last_error', models.CharField(blank=True, max_length=500, verbose_name='마지막 오류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='만든 시각')),
                ('next_attempt_at', models.DateTimeField(verbose_name='다음 시도 시각')),
                ('expires_at', models.DateTimeField(verbose_name='버리는 시각')),
                ('discarded_at', models.DateTimeField(blank=True, null=True, verbose_name='버린 시각')),
            ],
            options={
                'verbose_name': '보낼 메일',
                'verbose_name_plural': '보낼 메일',
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='accounts_mail_due_idx')],
            },
        ),
    ]
