# Generated by Django 6.1.1 on 2026-10-02 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_outgoingmail"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("login_ip_limited", "로그인: IP 시도 제한"),
                            ("login_failures_limited", "로그인: 비밀번호 틀림 제한"),
                            ("signup_ip_limited", "가입: IP 시도 제한"),
                            (
                                "signup_resend_ip_limited",
                                "가입 코드 재전송: IP 시도 제한",
                            ),
                            (
                                "password_reset_ip_limited",
                                "비밀번호 재설정: IP 시도 제한",
                            ),
                            (
                                "password_change_failures_limited",
                                "비밀번호 변경: 현재 비밀번호 틀림 제한",
                            ),
                        ],
                        max_length=40,
                        verbose_name="종류",
                    ),
                ),
                ("ip", models.CharField(max_length=64, verbose_name="IP")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="일어난 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="대상 계정",
                    ),
                ),
            ],
            options={
                "verbose_name": "보안 이벤트",
                "verbose_name_plural": "보안 이벤트",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="accounts_secevent_time_idx"
                    )
                ],
            },
        ),
    ]
