# Generated by Django 6.1.1 on 2026-10-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_securityevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("login_ip_limited", "로그인: IP 시도 제한"),
                    ("login_failures_limited", "로그인: 비밀번호 틀림 제한"),
                    (
                        "reserved_username_login",
                        "로그인: 예약어 아이디로 시도해 IP 차단",
                    ),
                    ("signup_ip_limited", "가입: IP 시도 제한"),
                    ("signup_resend_ip_limited", "가입 코드 재전송: IP 시도 제한"),
                    ("password_reset_ip_limited", "비밀번호 재설정: IP 시도 제한"),
                    (
                        "password_change_failures_limited",
                        "비밀번호 변경: 현재 비밀번호 틀림 제한",
                    ),
                ],
                max_length=40,
                verbose_name="종류",
            ),
        ),
    ]
