"""create scenario versions

Revision ID: 89f5d0983786
Revises: 7fafa6a64052
Create Date: 2026-10-04 11:30:44.674713

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '89f5d0983786'
down_revision: str | Sequence[str] | None = '7fafa6a64052'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'scenario_versions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('scenario_id', sa.Uuid(), nullable=False),
        sa.Column('number', sa.Integer(), nullable=False),
        sa.Column('note', sa.Text(), nullable=False),
        sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('char_length(note) <= 500', name=op.f('ck_scenario_versions_note_length')),
        sa.CheckConstraint('number >= 1', name=op.f('ck_scenario_versions_number_positive')),
        sa.ForeignKeyConstraint(
            ['scenario_id'],
            ['scenarios.asset_id'],
            name=op.f('fk_scenario_versions_scenario_id_scenarios'),
            ondelete='RESTRICT',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_versions')),
        sa.UniqueConstraint('scenario_id', 'number', name=op.f('uq_scenario_versions_scenario_id')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_versions')
    # ### end Alembic commands ###
