"""create table messages

Revision ID: af673c68f31e
Revises: c02d068e6339
Create Date: 2026-10-05 13:45:06.514878

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'af673c68f31e'
down_revision: str | Sequence[str] | None = 'c02d068e6339'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'table_messages',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('table_id', sa.Uuid(), nullable=False),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('character_name', sa.String(length=50), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('char_length(content) <= 500', name=op.f('ck_table_messages_content_length')),
        sa.CheckConstraint('sequence >= 1', name=op.f('ck_table_messages_sequence_positive')),
        sa.ForeignKeyConstraint(
            ['table_id'], ['game_tables.id'], name=op.f('fk_table_messages_table_id_game_tables'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_table_messages')),
        sa.UniqueConstraint('table_id', 'sequence', name=op.f('uq_table_messages_table_id')),
    )
    op.add_column(
        'game_tables', sa.Column('last_message_sequence', sa.Integer(), server_default=sa.text('0'), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_tables', 'last_message_sequence')
    op.drop_table('table_messages')
    # ### end Alembic commands ###
