"""create scenario lorebooks

Revision ID: 7fafa6a64052
Revises: 20481772a0b3
Create Date: 2026-10-04 10:17:37.965028

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7fafa6a64052'
down_revision: str | Sequence[str] | None = '20481772a0b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'scenario_lorebooks',
        sa.Column('scenario_id', sa.Uuid(), nullable=False),
        sa.Column('lorebook_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ['lorebook_id'],
            ['lorebooks.asset_id'],
            name=op.f('fk_scenario_lorebooks_lorebook_id_lorebooks'),
            ondelete='RESTRICT',
        ),
        sa.ForeignKeyConstraint(
            ['scenario_id'],
            ['scenarios.asset_id'],
            name=op.f('fk_scenario_lorebooks_scenario_id_scenarios'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('scenario_id', 'lorebook_id', name=op.f('pk_scenario_lorebooks')),
    )
    op.create_index(op.f('ix_scenario_lorebooks_lorebook_id'), 'scenario_lorebooks', ['lorebook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_lorebooks_lorebook_id'), table_name='scenario_lorebooks')
    op.drop_table('scenario_lorebooks')
    # ### end Alembic commands ###
