"""declaration outcome

Revision ID: 20a2740ca314
Revises: 3236bf8f835e
Create Date: 2026-10-06 05:36:02.114164

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '20a2740ca314'
down_revision: str | Sequence[str] | None = '3236bf8f835e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round_declarations', sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('round_declarations', 'outcome')
    # ### end Alembic commands ###
