"""table sheets

Revision ID: 4150f58cc3b5
Revises: 7f0ed387fdb7
Create Date: 2026-10-05 22:20:41.206455

"""

import json
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4150f58cc3b5'
down_revision: str | Sequence[str] | None = '7f0ed387fdb7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# 허용하는 캐릭터 방식의 조건. 하나는 있어야 하고, 정해진 값만 들어간다.
# 자동 생성은 이미 있는 테이블에 더한 CHECK 를 알아채지 못한다. 손으로 적는다
MODES_ALLOWED = "cardinality(character_modes) >= 1 AND character_modes <@ ARRAY['pregen', 'custom']::varchar[]"

# 있던 테이블의 방식을 그 테이블의 판(복사본)이 허용한 것으로 맞춘다.
# 방식이 적히지 않은 옛 복사본의 테이블은 칸의 기본값(둘 다 허용)에 머문다
COPY_MODES = """
    UPDATE game_tables
    SET character_modes = ARRAY(SELECT jsonb_array_elements_text(content -> 'character_modes'))::varchar[]
    WHERE jsonb_typeof(content -> 'character_modes') = 'array'
"""

# 시트가 없던 때에 시작한 테이블의 사람이 받는 시트. 옛 판을 읽을 때 채우는 기준 시트와 같은 값이다
BASELINE = {'abilities': {'str': 10, 'dex': 10, 'con': 10, 'int': 10, 'wis': 10, 'cha': 10}, 'max_hp': 10}

# 이미 진행 중인 테이블의 사람들에게 시트를 준다. "진행 중인 테이블의 사람은 모두 시트가 있다"를 있던 행에도 지킨다.
# 받을 시트는 앱이 시작할 때 찾는 순서와 같다. 고른 프리젠의 시트, 없으면 판의 기본 시트, 그것도 없으면 기준 시트.
# NULLIF: 문서 안의 null 은 SQL 의 NULL 이 아니다. COALESCE 가 건너뛰게 NULL 로 바꾼다
GIVE_SHEETS = """
    INSERT INTO table_sheets (id, table_id, user_id, abilities, max_hp, hp)
    SELECT
        gen_random_uuid(),
        members.table_id,
        members.user_id,
        source.sheet -> 'abilities',
        (source.sheet ->> 'max_hp')::smallint,
        (source.sheet ->> 'max_hp')::smallint
    FROM table_members AS members
    JOIN game_tables AS tables ON tables.id = members.table_id
    CROSS JOIN LATERAL (
        SELECT COALESCE(
            NULLIF(tables.content -> 'pregens' -> members.pregen_index -> 'sheet', 'null'::jsonb),
            NULLIF(tables.content -> 'default_sheet', 'null'::jsonb),
            CAST(:baseline AS JSONB)
        ) AS sheet
    ) AS source
    WHERE tables.status = 'playing'
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'table_sheets',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('table_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('abilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('max_hp', sa.SmallInteger(), nullable=False),
        sa.Column('hp', sa.SmallInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('hp BETWEEN 0 AND max_hp', name=op.f('ck_table_sheets_hp_range')),
        sa.CheckConstraint('max_hp >= 1', name=op.f('ck_table_sheets_max_hp_positive')),
        sa.ForeignKeyConstraint(
            ['table_id', 'user_id'],
            ['table_members.table_id', 'table_members.user_id'],
            name=op.f('fk_table_sheets_table_id_table_members'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_table_sheets')),
        sa.UniqueConstraint('table_id', 'user_id', name=op.f('uq_table_sheets_table_id')),
    )
    op.add_column(
        'game_tables',
        sa.Column(
            'character_modes',
            postgresql.ARRAY(sa.String(length=20)),
            server_default=sa.text("'{pregen,custom}'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
    op.create_check_constraint(op.f('ck_game_tables_character_modes_allowed'), 'game_tables', MODES_ALLOWED)
    op.execute(COPY_MODES)
    op.execute(sa.text(GIVE_SHEETS).bindparams(baseline=json.dumps(BASELINE)))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_tables', 'character_modes')
    op.drop_table('table_sheets')
    # ### end Alembic commands ###
