"""create table events

Revision ID: c02d068e6339
Revises: 40f8113fb600
Create Date: 2026-10-05 12:16:16.116028

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c02d068e6339'
down_revision: str | Sequence[str] | None = '40f8113fb600'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'table_events',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('table_id', sa.Uuid(), nullable=False),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=40), nullable=False),
        sa.Column('actor_id', sa.Uuid(), nullable=True),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('caused_by_sequence', sa.Integer(), nullable=True),
        sa.Column('action_group_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('caused_by_sequence < sequence', name=op.f('ck_table_events_cause_comes_first')),
        sa.CheckConstraint('sequence >= 1', name=op.f('ck_table_events_sequence_positive')),
        sa.ForeignKeyConstraint(
            ['table_id'], ['game_tables.id'], name=op.f('fk_table_events_table_id_game_tables'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_table_events')),
        sa.UniqueConstraint('table_id', 'sequence', name=op.f('uq_table_events_table_id')),
    )
    op.add_column('game_tables', sa.Column('last_sequence', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_tables', 'last_sequence')
    op.drop_table('table_events')
    # ### end Alembic commands ###
