"""round closing state

Revision ID: 32b4fdda6209
Revises: af673c68f31e
Create Date: 2026-10-05 16:44:03.673395

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '32b4fdda6209'
down_revision: str | Sequence[str] | None = 'af673c68f31e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_rounds', sa.Column('closing_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_rounds', 'closing_at')
    # ### end Alembic commands ###
