"""scenario sheets

Revision ID: 7f0ed387fdb7
Revises: 2f9f8f975f20
Create Date: 2026-10-05 20:52:18.760126

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7f0ed387fdb7'
down_revision: str | Sequence[str] | None = '2f9f8f975f20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# 허용하는 캐릭터 방식의 조건. 하나는 있어야 하고, 정해진 값만 들어간다.
# 자동 생성은 이미 있는 테이블에 더한 CHECK 를 알아채지 못한다. 손으로 적는다
MODES_ALLOWED = "cardinality(character_modes) >= 1 AND character_modes <@ ARRAY['pregen', 'custom']::varchar[]"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'scenarios',
        sa.Column(
            'character_modes',
            postgresql.ARRAY(sa.String(length=20)),
            server_default=sa.text("'{pregen,custom}'"),
            nullable=False,
        ),
    )
    op.add_column('scenarios', sa.Column('default_sheet', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###
    op.create_check_constraint(op.f('ck_scenarios_character_modes_allowed'), 'scenarios', MODES_ALLOWED)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'default_sheet')
    op.drop_column('scenarios', 'character_modes')
    # ### end Alembic commands ###
