"""create rounds

Revision ID: 40f8113fb600
Revises: 0ea14796067c
Create Date: 2026-10-05 09:20:34.780185

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '40f8113fb600'
down_revision: str | Sequence[str] | None = '0ea14796067c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'table_rounds',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('table_id', sa.Uuid(), nullable=False),
        sa.Column('number', sa.Integer(), nullable=False),
        sa.Column('scene', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint('number >= 1', name=op.f('ck_table_rounds_number_positive')),
        sa.ForeignKeyConstraint(
            ['table_id'], ['game_tables.id'], name=op.f('fk_table_rounds_table_id_game_tables'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_table_rounds')),
        sa.UniqueConstraint('table_id', 'number', name=op.f('uq_table_rounds_table_id')),
    )
    op.create_index(
        'uq_table_rounds_open', 'table_rounds', ['table_id'], unique=True, postgresql_where='closed_at IS NULL'
    )
    op.create_table(
        'round_declarations',
        sa.Column('round_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('character_name', sa.String(length=50), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('char_length(content) <= 1000', name=op.f('ck_round_declarations_content_length')),
        sa.ForeignKeyConstraint(
            ['round_id'],
            ['table_rounds.id'],
            name=op.f('fk_round_declarations_round_id_table_rounds'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('round_id', 'user_id', name=op.f('pk_round_declarations')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round_declarations')
    op.drop_index('uq_table_rounds_open', table_name='table_rounds', postgresql_where='closed_at IS NULL')
    op.drop_table('table_rounds')
    # ### end Alembic commands ###
