"""declaration action

Revision ID: 3236bf8f835e
Revises: 4150f58cc3b5
Create Date: 2026-10-06 00:09:36.840055

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3236bf8f835e'
down_revision: str | Sequence[str] | None = '4150f58cc3b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round_declarations', sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('round_declarations', 'action')
    # ### end Alembic commands ###
