"""create listings

Revision ID: bba6ecdc4659
Revises: 89f5d0983786
Create Date: 2026-10-04 16:48:44.946660

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'bba6ecdc4659'
down_revision: str | Sequence[str] | None = '89f5d0983786'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'listings',
        sa.Column('scenario_id', sa.Uuid(), nullable=False),
        sa.Column('version_id', sa.Uuid(), nullable=True),
        sa.Column('rating', sa.String(length=20), nullable=False),
        sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('tagline', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('genres', postgresql.ARRAY(sa.String(length=30)), nullable=False),
        sa.Column('tags', postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("rating IN ('all', 'adult')", name=op.f('ck_listings_rating_allowed')),
        sa.CheckConstraint(
            '(version_id IS NULL) = (published_at IS NULL)', name=op.f('ck_listings_published_together')
        ),
        sa.CheckConstraint('cardinality(genres) <= 3', name=op.f('ck_listings_genres_count')),
        sa.CheckConstraint('cardinality(tags) <= 10', name=op.f('ck_listings_tags_count')),
        sa.CheckConstraint('char_length(description) <= 5000', name=op.f('ck_listings_description_length')),
        sa.ForeignKeyConstraint(
            ['scenario_id'], ['scenarios.asset_id'], name=op.f('fk_listings_scenario_id_scenarios'), ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['version_id'],
            ['scenario_versions.id'],
            name=op.f('fk_listings_version_id_scenario_versions'),
            ondelete='RESTRICT',
        ),
        sa.PrimaryKeyConstraint('scenario_id', name=op.f('pk_listings')),
    )
    op.create_index(op.f('ix_listings_published_at'), 'listings', ['published_at'], unique=False)
    op.create_index(op.f('ix_listings_version_id'), 'listings', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_version_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_published_at'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
