"""create assets and worlds

Revision ID: 767f2ebb8306
Revises:
Create Date: 2026-10-03 22:30:42.836674

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '767f2ebb8306'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'assets',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('owner_id', sa.Uuid(), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('visibility', sa.String(length=20), nullable=False),
        sa.Column('rating', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("rating IN ('all', 'adult')", name=op.f('ck_assets_rating_allowed')),
        sa.CheckConstraint("type IN ('world')", name=op.f('ck_assets_type_allowed')),
        sa.CheckConstraint("visibility IN ('private')", name=op.f('ck_assets_visibility_allowed')),
        sa.CheckConstraint('char_length(description) <= 1000', name=op.f('ck_assets_description_length')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    )
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_table(
        'worlds',
        sa.Column('asset_id', sa.Uuid(), nullable=False),
        sa.Column('setting', sa.Text(), nullable=False),
        sa.Column('gm_notes', sa.Text(), nullable=False),
        sa.CheckConstraint('char_length(gm_notes) <= 4000', name=op.f('ck_worlds_gm_notes_length')),
        sa.CheckConstraint('char_length(setting) <= 8000', name=op.f('ck_worlds_setting_length')),
        sa.ForeignKeyConstraint(
            ['asset_id'], ['assets.id'], name=op.f('fk_worlds_asset_id_assets'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_worlds')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worlds')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
