"""create game tables

Revision ID: e6fe35d7175c
Revises: 96e599ded174
Create Date: 2026-10-04 23:20:48.128518

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e6fe35d7175c'
down_revision: str | Sequence[str] | None = '96e599ded174'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'game_tables',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('host_id', sa.Uuid(), nullable=False),
        sa.Column('version_id', sa.Uuid(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('opening_index', sa.SmallInteger(), nullable=False),
        sa.Column('capacity', sa.SmallInteger(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('rating', sa.String(length=20), nullable=False),
        sa.Column('invite_code', sa.String(length=12), nullable=False),
        sa.Column('is_public', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("rating IN ('all', 'adult')", name=op.f('ck_game_tables_rating_allowed')),
        sa.CheckConstraint("status IN ('recruiting', 'playing', 'ended')", name=op.f('ck_game_tables_status_allowed')),
        sa.CheckConstraint('capacity BETWEEN 1 AND 4', name=op.f('ck_game_tables_capacity_range')),
        sa.CheckConstraint('opening_index >= 0', name=op.f('ck_game_tables_opening_index_not_negative')),
        sa.ForeignKeyConstraint(
            ['version_id'],
            ['scenario_versions.id'],
            name=op.f('fk_game_tables_version_id_scenario_versions'),
            ondelete='RESTRICT',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_game_tables')),
        sa.UniqueConstraint('invite_code', name=op.f('uq_game_tables_invite_code')),
    )
    op.create_index(op.f('ix_game_tables_host_id'), 'game_tables', ['host_id'], unique=False)
    op.create_index(op.f('ix_game_tables_version_id'), 'game_tables', ['version_id'], unique=False)
    op.create_table(
        'table_members',
        sa.Column('table_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('character_name', sa.String(length=50), nullable=True),
        sa.Column('character_description', sa.Text(), nullable=False),
        sa.Column('pregen_index', sa.SmallInteger(), nullable=True),
        sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint(
            'char_length(character_description) <= 1000', name=op.f('ck_table_members_description_length')
        ),
        sa.CheckConstraint(
            'character_name IS NOT NULL OR pregen_index IS NULL', name=op.f('ck_table_members_pregen_needs_character')
        ),
        sa.ForeignKeyConstraint(
            ['table_id'], ['game_tables.id'], name=op.f('fk_table_members_table_id_game_tables'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('table_id', 'user_id', name=op.f('pk_table_members')),
        sa.UniqueConstraint('table_id', 'pregen_index', name=op.f('uq_table_members_table_id')),
    )
    op.create_index(op.f('ix_table_members_user_id'), 'table_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_members_user_id'), table_name='table_members')
    op.drop_table('table_members')
    op.drop_index(op.f('ix_game_tables_version_id'), table_name='game_tables')
    op.drop_index(op.f('ix_game_tables_host_id'), table_name='game_tables')
    op.drop_table('game_tables')
    # ### end Alembic commands ###
